variables:
    GIT_SUBMODULE_STRATEGY: normal

before_script:
    - cd /builds/maplestory/maplestory.io/PKG1
    - git checkout master
    - git pull origin master
    - cd /builds/maplestory/maplestory.io/WZData
    - git checkout master
    - git pull origin master

stages:
    - build

ubuntu-14_04:
    stage: build
    tags:
        - dotnet-2.0
    script:
        - dotnet --info
        - cd /builds/maplestory/maplestory.io
        - dotnet restore -r ubuntu.14.04-x64
        - dotnet publish -r ubuntu.14.04-x64
    artifacts:
        name: "NETCoreApp-ubuntu.14.04-x64"
        paths:
            - /builds/maplestory/maplestory.io/maplestory.io/bin/Debug/netcoreapp1.1/ubuntu.14.04-x64/publish

ubuntu-16_04:
    stage: build
    tags:
        - dotnet-2.0
    script:
        - dotnet --info
        - cd /builds/maplestory/maplestory.io
        - dotnet restore -r ubuntu.16.04-x64
        - dotnet publish -r ubuntu.16.04-x64
    artifacts:
        name: "NETCoreApp-ubuntu.16.04-x64"
        paths:
            - /builds/maplestory/maplestory.io/maplestory.io/bin/Debug/netcoreapp1.1/ubuntu.16.04-x64/publish

win10-x64:
    stage: build
    tags:
        - dotnet-2.0
    script:
        - dotnet --info
        - cd /builds/maplestory/maplestory.io
        - dotnet restore -r win10-x64
        - dotnet publish -r win10-x64
    artifacts:
        name: "NETCoreApp-ubuntu.16.04-x64"
        paths:
            - /builds/maplestory/maplestory.io/maplestory.io/bin/Debug/netcoreapp1.1/win10-x64/publish

win8-x64:
    stage: build
    tags:
        - dotnet-2.0
    script:
        - dotnet --info
        - cd /builds/maplestory/maplestory.io
        - dotnet restore -r win8-x64
        - dotnet publish -r win8-x64
    artifacts:
        name: "NETCoreApp-ubuntu.16.04-x64"
        paths:
            - /builds/maplestory/maplestory.io/maplestory.io/bin/Debug/netcoreapp1.1/win8-x64/publish

osx:
    stage: build
    tags:
        - dotnet-2.0
    script:
        - dotnet --info
        - cd /builds/maplestory/maplestory.io
        - dotnet restore -r osx.10.12-x64
        - dotnet publish -r osx.10.12-x64
    artifacts:
        name: "NETCoreApp-ubuntu.16.04-x64"
        paths:
            - /builds/maplestory/maplestory.io/maplestory.io/bin/Debug/netcoreapp1.1/osx.10.12-x64/publish

ubuntu-14_04_release:
    stage: build
    tags:
        - dotnet-2.0
    script:
        - dotnet --info
        - cd /builds/maplestory/maplestory.io
        - dotnet restore -r ubuntu.14.04-x64
        - dotnet publish -r ubuntu.14.04-x64 -c Release
    artifacts:
        name: "NETCoreApp-ubuntu.14.04-x64"
        paths:
            - /builds/maplestory/maplestory.io/maplestory.io/bin/Release/netcoreapp1.1/ubuntu.14.04-x64/publish

ubuntu-16_04_release:
    stage: build
    tags:
        - dotnet-2.0
    script:
        - dotnet --info
        - cd /builds/maplestory/maplestory.io
        - dotnet restore -r ubuntu.16.04-x64
        - dotnet publish -r ubuntu.16.04-x64 -c Release
    artifacts:
        name: "NETCoreApp-ubuntu.16.04-x64"
        paths:
            - /builds/maplestory/maplestory.io/maplestory.io/bin/Release/netcoreapp1.1/ubuntu.16.04-x64/publish

win10-x64_release:
    stage: build
    tags:
        - dotnet-2.0
    script:
        - dotnet --info
        - cd /builds/maplestory/maplestory.io
        - dotnet restore -r win10-x64
        - dotnet publish -r win10-x64 -c Release
    artifacts:
        name: "NETCoreApp-ubuntu.16.04-x64"
        paths:
            - /builds/maplestory/maplestory.io/maplestory.io/bin/Release/netcoreapp1.1/win10-x64/publish

win8-x64_release:
    stage: build
    tags:
        - dotnet-2.0
    script:
        - dotnet --info
        - cd /builds/maplestory/maplestory.io
        - dotnet restore -r win8-x64
        - dotnet publish -r win8-x64 -c Release
    artifacts:
        name: "NETCoreApp-ubuntu.16.04-x64"
        paths:
            - /builds/maplestory/maplestory.io/maplestory.io/bin/Release/netcoreapp1.1/win8-x64/publish

osx_release:
    stage: build
    tags:
        - dotnet-2.0
    script:
        - dotnet --info
        - cd /builds/maplestory/maplestory.io
        - dotnet restore -r osx.10.12-x64
        - dotnet publish -r osx.10.12-x64 -c Release
    artifacts:
        name: "NETCoreApp-ubuntu.16.04-x64"
        paths:
            - /builds/maplestory/maplestory.io/maplestory.io/bin/Release/netcoreapp1.1/osx.10.12-x64/publish