variables:
    GIT_SUBMODULE_STRATEGY: recursive

stages:
    - build
    - image
    - deploy

build:
    stage: build
    image: microsoft/dotnet:2.1-sdk
    script:
        - dotnet --info
        - cd $CI_PROJECT_DIR
        - ls -lh
        - dotnet restore
        - dotnet publish -c Release
    artifacts:
        name: "MapleStory.IO"
        paths:
            - /builds/maplestory/maplestory.io/maplestory.io/bin/Release/netcoreapp2.1/

docker_image:
    only:
        - master
    tags:
        - docker
    stage: image
    image: docker:stable
    services:
        - docker:dind
    script:
        - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} registry.crr.io
        - echo ${CI_COMMIT_SHA:0:8} > SHA1.hash
        - docker build -t registry.crr.io/${CI_PROJECT_PATH}:latest .
        - docker push registry.crr.io/${CI_PROJECT_PATH}:latest
        - docker tag registry.crr.io/${CI_PROJECT_PATH}:latest registry.crr.io/${CI_PROJECT_PATH}:${CI_COMMIT_SHA:0:8}
        - docker push registry.crr.io/${CI_PROJECT_PATH}:${CI_COMMIT_SHA:0:8}

kubernetes_deploy:
    only:
        - master
    stage: deploy
    image: registry.crr.io/crrio/kubernetes-deploy:latest
    environment:
        name: maplestory.io
        url: https://maplestory.io/
    script:
        - ~/kubectl set image deployment/io io=registry.crr.io/${CI_PROJECT_PATH}:${CI_COMMIT_SHA:0:8} --namespace=maplestory
