variables:
    GIT_SUBMODULE_STRATEGY: recursive

stages:
    - build
    - image
    - test
    - image_pass

build:
    stage: build
    image: microsoft/dotnet:2.1-sdk
    script:
        - ls -lh
        - dotnet restore
        - dotnet publish -c Release -o build maplestory.io
        - ls -lh maplestory.io
    artifacts:
        name: "MapleStory.IO"
        paths:
            - maplestory.io/build

docker_image:
    only:
        - master
    tags:
        - docker
    stage: image
    image: docker:stable
    services:
        - docker:dind
    script:
        - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} registry.crr.io
        - echo ${CI_COMMIT_SHA:0:8} > SHA1.hash
        - docker build -t registry.crr.io/${CI_PROJECT_PATH}:${CI_COMMIT_SHA:0:8} .
        - docker push registry.crr.io/${CI_PROJECT_PATH}:${CI_COMMIT_SHA:0:8}

test:
    stage: test
    only:
        - master
    image: registry.crr.io/${CI_PROJECT_PATH}:${CI_COMMIT_SHA:0:8}
    script:
        - echo 'TODO More comprehensive tests once S3 migration is complete'
        - /bin/wait-for-it.sh -t 120 127.0.0.1:5000
        - curl --silent --show-error --fail -o /dev/null localhost:5000 && echo 'Successfully loaded home page'

docker_image_latest:
    stage: image_pass
    only:
        - master
    tags:
        - docker
    image: docker:stable
    services:
        - docker:dind
    script:
        - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} registry.crr.io
        - docker pull registry.crr.io/${CI_PROJECT_PATH}:${CI_COMMIT_SHA:0:8}
        - docker tag registry.crr.io/${CI_PROJECT_PATH}:${CI_COMMIT_SHA:0:8} registry.crr.io/${CI_PROJECT_PATH}:latest
        - docker push registry.crr.io/${CI_PROJECT_PATH}:latest

kubernetes_deploy:
    only:
        - master
    stage: image_pass
    image: registry.crr.io/crrio/kubernetes-deploy:latest
    environment:
        name: maplestory.io
        url: https://maplestory.io/
    script:
        - ~/kubectl set image deployment/io io=registry.crr.io/${CI_PROJECT_PATH}:${CI_COMMIT_SHA:0:8} --namespace=maplestory
